### ISSUE TITLE
ETA for F0F removal?

### ISSUE THREAD

**Issue by Kubik-Rubik** [SniperSister/ComFlexforms#11]
Hi David,
I know, we already spoke about this briefly. Do you have an ETA when you remove the dependency of F0F?
I like the flexibility of this component but don't want to use the outdated framework in my projects.
Cheers

**Comment by SniperSister** [comment]
Hi Viktor,

it's on my (football-field size) todo list. I can't give you an exact date, but sometime in the first half of 2019 should work.

**Comment by Kubik-Rubik** [comment]
Great, sounds good to me!
